name: CI

concurrency: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  PoetrySetup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python -
          export PATH="$HOME/.poetry/bin:$PATH"
      - name: Cache Poetry
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m poetry install

  Lint:
    runs-on: ubuntu-latest
    needs: PoetrySetup
    steps:
      - name: Black check
        run: poetry run black . --check
      - name: Isort check
        run: poetry run isort . --check

  UnitTests:
    runs-on: ubuntu-latest
    needs: PoetrySetup
    steps:
      - name: Run tests
        run: poetry run pytest .
